### ISSUE TITLE
separate "service" and "client" packages?

### ISSUE THREAD

**Issue by balmas** [alpheios-project/lexis-cs#13]
I'm a little confused about the separation between the client and service code in the lexis-cs package and the way the event handlers are initialized. 

Currently, the cedict-service/service.js registered a document event listener as follows:

```
document.addEventListener('DOMContentLoaded', () => {
  const service = new MessagingService(messagingServiceName, new Destination(CedictDestinationConfig))
  service.registerReceiverCallback(CedictDestinationConfig.name, messageHandler)

  try {
    cedictData = new Cedict(CedictConfig)
  } catch (error) {
    console.error(error)
    return
  }
  cedictData.init().then(() => {
    // TODO: A message to ease manual testing. Shall be removed in production
    console.log('CEDICT service is ready')
  }).catch((error) => console.error(error))
})
```

It looks to me like this code gets called twice - once from the iframe that acts as the "service" side and once by the client code in alpheios components

I think we will need a way for uses of the lexis-cs code to be able to register themselves in the role of either client or service, and have control over when and how the messaging service gets initialized.
It looks to me that this means that the way the document.

**Comment by balmas** [comment]
@kirlat can you help me understand this?

**Comment by balmas** [comment]
![Screenshot from 2020-01-29 15-08-23](https://user-images.githubusercontent.com/644870/73393258-5e773b80-42a9-11ea-9962-b1ce7d0c2806.png)

The above screenshot is from a page with the embed-lib loaded. You can see that actually the domContentLoaded event has been added to the main document twice

Interestingly, when I check the eventListeners on a page with the webextension active, the main page does not have any extra dom contented loaded event handlers added to it.

**Comment by kirlat** [comment]
Thanks for a very good catch! I think it started to happen after we've moved `CedictDestinationConfig` to `service.js`. This configuration is exported by LexisCS and is used in Client Adapters and in Components too. As a result of that, the whole content of `service.js` is included by webpack into the components bundle. Because `document.addEventListener()` is in a body of the `service.js` file it is inserted into the body of a components bundle too and thus gets executed once components are loaded.

The best solution to this, I think, would be to move all constants of LexisCS into a `constants.js` file and expose that file, not `service.js`, to the outside world. That will solve the problem and will also make a bundle more compact. What do you think about that solution?

Testing this I've got one more reminder of how complex our architecture is becoming. In order to put this fix into embed-lib I had to update LexisCS, rebuild it, and then rebuild client adapters, components, and embed lib at last. All that just to see the results of the change in the final bundle. I'm afraid to think how many PRs would this little change produce. I think we should do all we can to simplify that.

**Comment by balmas** [comment]
> The best solution to this, I think, would be to move all constants of LexisCS into a `constants.js` file and expose that file, not `service.js`, to the outside world. That will solve the problem and will also make a bundle more compact. What do you think about that solution?
> 

Ok

> Testing this I've got one more reminder of how complex our architecture is becoming. In order to put this fix into embed-lib I had to update LexisCS, rebuild it, and then rebuild client adapters, components, and embed lib at last. All that just to see the results of the change in the final bundle. I'm afraid to think how many PRs would this little change produce. I think we should do all we can to simplify that.

Agreed
